[[repos]]
url = "localhost"
name = "LOCAL"
definitions_version = 0

[[repos.themes]]
name = "rondao"
directory = "/home/rondao/.config/leftwm/themes/rondao"
version = "0.0.0"
leftwm_versions = "*"
current = true
