#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s ${SCRIPTPATH}/down /tmp/leftwm-theme-down

#boot compton or picom if it exists
if [ -x "$(command -v picom)" ]; then
  picom --experimental-backends --config $SCRIPTPATH/picom.conf &
elif [ -x "$(command -v compton)" ]; then
  compton &> /dev/null &
fi

#set background (and colorscheme with pywal)
if [ -x "$(command -v wal)" ]; then
  wal -i "${SCRIPTPATH}/wallpapers/"
  (cat ~/.cache/wal/sequences &)
elif [ -x "$(command -v feh)" ]; then
  feh --bg-fill --randomize "${SCRIPTPATH}/wallpapers/"
fi

#set the theme.toml config
if [ -x "$(command -v wal)" ]; then
  leftwm command "LoadTheme $HOME/.cache/wal/leftwm-theme.toml"
else
  leftwm command "LoadTheme $SCRIPTPATH/theme.toml"
fi

#boot a polybar for each monitor
cd ${SCRIPTPATH}/polybar
polybar -m | sed s/:.*// | tac | while read -r monitor
do
  monitor=$monitor polybar -c config.ini main &> /dev/null &
done

